### ISSUE TITLE
The screen remains black during the cutscene and won't progress.

### ISSUE THREAD

**Issue by shin-t-o** [an-anime-team/the-honkers-railway-launcher#304]
I've been using this launcher for a long time. However, since this particular issue remains unsolved no matter how much time passes, I'm reaching out to inquire about it.

- switching between X11 and Wayland
- reinstalling the launcher and game
- repairing the game
- switching the in-game language
- switching Wine versions whenever possible
- switching DXVK versions whenever possible
- copying missing DLL files from Windows based on the log file

Despite trying everything I could think of, I could never get it to render. Is there a solution?

<img width="500" src="https://github.com/user-attachments/assets/e16fe491-e1bb-4308-b8b1-1bbfa21a8957" />

[game.log](https://github.com/user-attachments/files/24330658/game.log)
[debug.log](https://github.com/user-attachments/files/24330659/debug.log)

**Comment by NelloKudo** [comment]
First of all, the debug log shows you're still on a very old launcher version (1.10.0, we're currently at 1.14.2), so make sure to update that.

Then the video not playing issue should be solved in all the Spritz runners, I recommend doing the following:
- Update the launcher to 1.14.2
- Open launcher folder from the top right button, delete the `prefix` one
- Reopen the launcher, let it create prefix and install DXVK again and see then.

If the issue persists then it's likely some dependency missing on your system, such as `gst-libav` or other gstreamer packages. Those are packaged within the Flatpak version of the launcher, so give that a try too if you can't fix this no matter what.

**Comment by shin-t-o** [comment]
@NelloKudo 
Thank you for your prompt response.

These fixes didn't resolve the issue, but it appears that the GStreamer packages were the cause.
```markdown
- update the launcher
- delete the prefix one
- create prefix and install DXVK again
```

After installing `gstreamer1.0-plugins-bad` , the program started crashing(not remains black) during movie scenes. Replacing `mfc140u.dll` resolved the issue, and playback now works properly.
